apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: chat
  name: chat
  namespace: default
spec:
  serviceName: "chat-svc"
  replicas: 4
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - image: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-chat:latest
        name: chat
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 3002
          name: chat-container
  volumeClaimTemplates: [] # 여기에 PersistentVolumeClaim을 정의해야 합니다.
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
  name: chat-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: https
    name: https
  - protocol: TCP
    port: 3002
    targetPort: chat-container
    name: chat
  clusterIP: None
  selector:
    app: chat
