apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-chat
  newName: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-chat
  newTag: "3.1"
- name: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-front
  newName: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-front
  newTag: "94.1"
- name: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-hls
  newName: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-hls
  newTag: "29.1"
- name: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-sfu
  newName: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-sfu
  newTag: "13.1"
- name: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-spring
  newName: 135685504741.dkr.ecr.ap-northeast-2.amazonaws.com/tmeroom-spring
  newTag: "22.1"
resources:
- ../../base
